### ISSUE TITLE
[Gitlab] Assignee will be Reviewer after backport

### ISSUE THREAD

**Issue by shyim** [kiegroup/git-backporting#90]
PR:

![image](https://github.com/kiegroup/git-backporting/assets/6224096/f7b94425-962d-499b-9e13-e3501d401101)

Backport:

![image](https://github.com/kiegroup/git-backporting/assets/6224096/b0d85262-25eb-4fad-9c95-10783dcf35b9)

**Comment by lampajr** [comment]
Hey @shyim, I am not sure the sentence `Assignee will be Reviewer after backport` is true.
If I recall by default if `--reviewers` is not provided (or empty) and `--no-inherit-reviewers` is set to true (which is the default) the backport PR will set as reviewers the `author` and who `merged` the original one.

In this case the assignee is marked as reviewer in the backport because I guess it is the author of the original PR and the assumption is that the original PR author is a good candidate to review the backport one - or at least this was our initial use case.

PS: if you want to override this behavior you can just provide `--reviewers` arg with the list of reviewers of your choice

**Comment by shyim** [comment]
AHHH. Thanks for the explanation.

**Comment by lampajr** [comment]
[edit]
If I recall by default if `--reviewers` is not provided (or empty) and `--no-inherit-reviewers` is set to ~~true~~ false (which is the default) the backport PR will set as reviewers the `author` and who `merged` the original one.

@shyim for correctness `--no-inherit-reviewers` should be false to actually inherit `author` and `merger` as reviewers in backport PR
